# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Scriptorium Vincentii
# tagline:             'A place for my 2 cents on stuffs'
#description:         '<img src="https://github.com/vstoliaroff/vstoliaroff.info/public/scriptorium.png" height=60 </img>' 
url:                 http://vstoliaroff.info
baseurl:             ''
paginate:            5

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  #- jekyll-gist
  #- jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "page:num"

google_analytics: UA-89702446-1

# About/contact
author:
  name:              Vincent Stoliaroff
  url:               http://vstoliaroff.info
  email:             vstoliaroff@gmail.com


