---
title: "Representing tree structures in Rmarkdown documents"
layout: post
comments: true
tags: [classification]
---


Let's say, I want to display the ontology of different linear methods of classification in the form of an entity relationship diagram.  
Based on the grouping detailled in the chapter IV of the book [Element of Statistical Learning](http://statweb.stanford.edu/~tibs/ElemStatLearn/)
We can use some javascript libraries or `R` packages to do so. 


testing it using another solution (line block)...

+-- Linear Method for classification
| +-- Model Discriminant Function for each class
| | +-- Linear Regression of an Indicator Matrix
| | +-- Discriminant Function is the a posteriori Probability
| | | +-- Logistic Regression
| | | +-- Linear Discriminant Analysis
| +-- Model the decision Boundaries directly
| | +-- Perceptron (Rosenblatt 1958)
| | +-- Vapnik (1996)
| | | +-- Optimally separating hyperplan (separable case: )
| | | +-- Hyperplan that minimizes some measure of overlap (non separable case: chapter 12)
